name: Build Artifact

on:
  push:
    branches: ["dev"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      # - name: Analyze
      #   run: flutter analyze .

      - name: Build APK (release)
        run: flutter build apk --release

      - name: List outputs (debugging)
        run: ls -R build/app/outputs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Pakai glob yang aman untuk berbagai versi/flavor:
          path: |
            build/app/outputs/flutter-apk/*release*.apk
            build/app/outputs/apk/release/*.apk
